Repository Suada-Learning/suada-components, pull requests merged in 2025-02, with the labels that each got.

#53 feat: add customSwitcher component story
  dist/components/Switcher/CustomSwitcher.d.ts
  dist/components/Switcher/CustomSwitcher.interface.d.ts
  dist/components/Switcher/CustomSwitcher.interface.js
  dist/components/Switcher/CustomSwitcher.interface.js.map
  dist/components/Switcher/CustomSwitcher.js
  dist/components/Switcher/CustomSwitcher.js.map
  dist/components/Switcher/CustomSwitcher.stories.d.ts
  dist/components/Switcher/CustomSwitcher.stories.js
  dist/components/Switcher/CustomSwitcher.stories.js.map
  dist/components/Switcher/CustomSwitcher.styles.d.ts
  dist/components/Switcher/CustomSwitcher.styles.js
  dist/components/Switcher/CustomSwitcher.styles.js.map
  dist/components/Switcher/Switcher.d.ts
  dist/components/Switcher/Switcher.js
  dist/components/Switcher/Switcher.js.map
  dist/components/Switcher/index.d.ts
  dist/components/Switcher/index.js
  dist/components/Switcher/index.js.map
  dist/index.d.ts
  dist/index.esm.js
  dist/index.esm.js.map
  dist/index.js
  dist/index.js.map
  dist/types/components/Switcher/CustomSwitcher.d.ts
  dist/types/components/Switcher/CustomSwitcher.interface.d.ts
  dist/types/components/Switcher/CustomSwitcher.styles.d.ts
  dist/types/components/Switcher/Switcher.d.ts
  dist/types/components/Switcher/index.d.ts
  dist/types/index.d.ts
  src/components/Switcher/CustomSwitcher.interface.ts
  src/components/Switcher/CustomSwitcher.stories.tsx
  src/components/Switcher/CustomSwitcher.styles.ts
  src/components/Switcher/CustomSwitcher.tsx
  src/components/Switcher/Switcher.tsx
  src/components/Switcher/index.ts
  src/index.ts
Labels: Review Required

#51 feat: add icon.stories.tsx file
  dist/components/Icons/Icons.stories.d.ts
  dist/components/Icons/Icons.stories.js
  dist/components/Icons/Icons.stories.js.map
  src/components/Icons/Icons.stories.tsx
Labels: Review Required

#55 refactor: export svg from icons file
  dist/components/CourseCard/CourseCard.styles.d.ts
  dist/icons.d.ts
  dist/icons.js
  dist/icons.js.map
  dist/index.d.ts
  dist/index.esm.js
  dist/index.esm.js.map
  dist/index.js
  dist/index.js.map
  dist/types/components/CourseCard/CourseCard.styles.d.ts
  dist/types/icons.d.ts
  dist/types/index.d.ts
  src/icons.ts
  src/index.ts
Labels: Review Required

#56 feat: add export example in json
  package.json
Labels: Review Required

#57 refactor: change import url
  dist/components/CourseCard/CourseCard.styles.d.ts
  dist/index.d.ts
  dist/index.esm.js
  dist/index.esm.js.map
  dist/index.js
  dist/index.js.map
  dist/types/components/CourseCard/CourseCard.styles.d.ts
  dist/types/index.d.ts
  package.json
  src/icons.ts
  src/index.ts
Labels: Review Required

#58 refactor: return old code
  dist/index.d.ts
  dist/index.js
  dist/index.js.map
  dist/types/index.d.ts
  src/index.ts
Labels: Review Required

#64 feat: export closeIcon
  dist/index.d.ts
  dist/index.esm.js
  dist/index.esm.js.map
  dist/index.js
  dist/index.js.map
  dist/svg/AddIcon.js
  dist/svg/index.d.ts
  dist/svg/index.js
  dist/svg/index.js.map
  dist/types/index.d.ts
  dist/types/svg/index.d.ts
  src/index.ts
  src/svg/AddIcon.tsx
  src/svg/index.ts
Labels: Review Required

#61 Feat/d.profile drop down & sidebar init
  .storybook/withProviders.tsx
  README.md
  package.json
  src/components/CourseCard/CourseCard.interface.ts
  src/components/ExpansionMenu/ExpansionItem.interface.tsx
  src/components/ExpansionMenu/ExpansionItem.tsx
  src/components/ExpansionMenu/ExpansionNavMenu.tsx
  src/components/ExpansionMenu/NavigationBar.stories.tsx
  src/components/ExpansionMenu/NavigationBar.tsx
  src/components/ExpansionMenu/index.ts
  src/components/ExpansionMenu/routerConfig.tsx
  src/components/ExpansionMenu/styled-components.ts
  src/components/ProfileDropdown/ProfileDropDown.stories.tsx
  src/components/ProfileDropdown/ProfileDropdown.tsx
  src/components/ProfileDropdown/index.ts
  src/components/ProfileDropdown/styled-components.ts
  src/components/ProfilePicture/ProfilePicture.styles.tsx
  src/components/ProfilePicture/ProfilePicture.tsx
  src/components/ProfilePicture/profilePicture.interface.ts
  src/svg/Analytics.tsx
  src/svg/Circle.tsx
  src/svg/Company.tsx
  src/svg/Learning.tsx
  src/svg/Library.tsx
  src/svg/UsersIcon.tsx
  src/svg/index.ts
  yarn.lock
Labels: Review Required

#66 feat: add DropDown component
  package.json
  src/components/DropDown/DropDown.interface.ts
  src/components/DropDown/DropDown.stories.tsx
  src/components/DropDown/DropDown.styles.ts
  src/components/DropDown/DropDown.tsx
  src/components/DropDown/index.ts
  src/index.ts
  yarn.lock
Labels: Review Required

#65 refactor: change svg sizes
  dist/index.esm.js
  dist/svg/AddIcon.js
  dist/svg/CloseIcon.js
  src/svg/AddIcon.tsx
  src/svg/CloseIcon.tsx
Labels: Review Required

#69 feat: add and export material icons as component
  dist/index.d.ts
  dist/index.esm.js
  dist/index.esm.js.map
  dist/index.js
  dist/index.js.map
  dist/svg/BusinessIcon.d.ts
  dist/svg/BusinessIcon.js
  dist/svg/BusinessIcon.js.map
  dist/svg/EmailIcon.d.ts
  dist/svg/EmailIcon.js
  dist/svg/EmailIcon.js.map
  dist/svg/EventIcon.d.ts
  dist/svg/EventIcon.js
  dist/svg/EventIcon.js.map
  dist/svg/LocationCityIcon.d.ts
  dist/svg/LocationCityIcon.js
  dist/svg/LocationCityIcon.js.map
  dist/svg/LocationOnIcon.d.ts
  dist/svg/LocationOnIcon.js
  dist/svg/LocationOnIcon.js.map
  dist/svg/MarkunreadMailboxIcon.d.ts
  dist/svg/MarkunreadMailboxIcon.js
  dist/svg/MarkunreadMailboxIcon.js.map
  dist/svg/Person.d.ts
  dist/svg/Person.js
  dist/svg/Person.js.map
  dist/svg/PhoneIphoneIcon.d.ts
  dist/svg/PhoneIphoneIcon.js
  dist/svg/PhoneIphoneIcon.js.map
  dist/svg/PublicIcon.d.ts
  dist/svg/PublicIcon.js
  dist/svg/PublicIcon.js.map
  dist/svg/index.d.ts
  dist/svg/index.js
  dist/svg/index.js.map
  dist/types/index.d.ts
  dist/types/svg/BusinessIcon.d.ts
  dist/types/svg/EmailIcon.d.ts
  dist/types/svg/EventIcon.d.ts
  dist/types/svg/LocationCityIcon.d.ts
  dist/types/svg/LocationOnIcon.d.ts
  dist/types/svg/MarkunreadMailboxIcon.d.ts
  dist/types/svg/Person.d.ts
  dist/types/svg/PhoneIphoneIcon.d.ts
  dist/types/svg/PublicIcon.d.ts
  dist/types/svg/index.d.ts
  src/index.ts
  src/svg/BusinessIcon.tsx
  src/svg/EmailIcon.tsx
  src/svg/EventIcon.tsx
  src/svg/LocationCityIcon.tsx
  src/svg/LocationOnIcon.tsx
  src/svg/MarkunreadMailboxIcon.tsx
  src/svg/Person.tsx
  src/svg/PhoneIphoneIcon.tsx
  src/svg/PublicIcon.tsx
  src/svg/index.ts
Labels: Review Required

#71 feat: add input component
  src/components/DropDown/DropDown.tsx
  src/components/Input/Input.interface.ts
  src/components/Input/Input.scss
  src/components/Input/Input.stories.tsx
  src/components/Input/Input.tsx
  src/components/Input/index.ts
  src/components/Input/styled-components.ts
  src/components/SearchInput/SearchInput.tsx
  src/components/TextInput/index.ts
Labels: Review Required

#73 feat: add DatePicker component with styled components and interface
  package.json
  src/components/DatePicker/DatePicker.stories.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/datePicker.interface.ts
  src/components/DatePicker/index.ts
  src/components/DatePicker/styled-components.ts
  src/index.ts
  yarn.lock
Labels: Review Required

#76 Feat/d.pagination component
  src/components/CheckboxV2/Checkbox.stories.tsx
  src/components/CheckboxV2/Checkbox.tsx
  src/components/CheckboxV2/checkboxV2.interface.ts
  src/components/CheckboxV2/index.ts
  src/components/CheckboxV2/styled-components.ts
  src/components/PaginationV2/Pagination.stories.tsx
  src/components/PaginationV2/Pagination.tsx
  src/components/PaginationV2/TablePagination.tsx
  src/components/PaginationV2/index.ts
  src/components/PaginationV2/pagination.interface.ts
  src/components/PaginationV2/styled-components.ts
  src/components/PhoneCountyCodeV2/PhoneCountyCode.tsx
  src/index.ts
Labels: Review Required

#75 feat: add Checkbox component with customizable label and tooltip
  src/components/CheckboxV2/Checkbox.stories.tsx
  src/components/CheckboxV2/Checkbox.tsx
  src/components/CheckboxV2/checkboxV2.interface.ts
  src/components/CheckboxV2/index.ts
  src/components/CheckboxV2/styled-components.ts
  src/components/PhoneCountyCodeV2/PhoneCountyCode.tsx
  src/index.ts
Labels: Review Required

#77 feat: add Loader component with customizable size and background options
  src/components/Loader/Loader.stories.tsx
  src/components/Loader/Loader.tsx
  src/components/Loader/index.ts
  src/components/Loader/loader.interface.ts
  src/components/Loader/styled-components.ts
  src/index.ts
Labels: Change(s) requested

#80 feat: add VideoPlayer component with HLS.js support
  package.json
  src/components/VideoPlayer/Player.jsx
  src/components/VideoPlayer/VideoPlayer.stories.tsx
  src/components/VideoPlayer/VideoPlayer.tsx
  src/components/VideoPlayer/index.ts
  src/components/VideoPlayer/styled-components.ts
  yarn.lock
Labels: Review Required

#88 feat: add CustomTooltip and TooltipHeight components with stories
  src/components/Tooltip/CustomTooltip.stories.tsx
  src/components/Tooltip/CustomTooltip.tsx
  src/components/Tooltip/TooltipHeight.stories.tsx
  src/components/Tooltip/TooltipHeight.tsx
  src/components/Tooltip/customTooltip.interface.ts
  src/components/Tooltip/index.ts
  src/components/Tooltip/toolTipHeight.interface.ts
  src/index.ts
Labels: Ready To Merge

#84 feat: add Badge component with styled components and Storybook stories
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/Badge.tsx
  src/components/Badge/index.ts
  src/components/Badge/styled-components.ts
  src/index.ts
Labels: Ready To Merge

#87 feat: add ColorPicker component with color selection functionality
  package.json
  src/components/ColorPicker/ColorPicker.stories.tsx
  src/components/ColorPicker/ColorPicker.tsx
  src/components/ColorPicker/colorPicker.interface.ts
  src/components/ColorPicker/colors.ts
  src/components/ColorPicker/index.ts
  src/components/ColorPicker/styled.components.ts
  src/index.ts
  yarn.lock
Labels: Ready To Merge

#86 feat: add Tile component with styled elements and HorizontalArrow icon
  src/components/Tile/HorizontalArrow.tsx
  src/components/Tile/Tile.stories.tsx
  src/components/Tile/Tile.tsx
  src/components/Tile/index.tsx
  src/components/Tile/styled-components.ts
  src/components/Tile/tile.interface.ts
  src/index.ts
Labels: Ready To Merge

#85 feat: add Breadcrumb component with styled components and Storybook s…
  src/components/BreadCrumb/BreadCrumb.stories.tsx
  src/components/BreadCrumb/Breadcrumb.tsx
  src/components/BreadCrumb/index.ts
  src/components/BreadCrumb/styled-components.ts
  src/components/BreadCrumb/types.ts
  src/index.ts
Labels: Ready To Merge

#90 feat: add ColumnNavigation component with styled components and Story…
  src/components/ColumnNavigation/ColumnNavigation.stories.tsx
  src/components/ColumnNavigation/ColumnNavigation.tsx
  src/components/ColumnNavigation/columnNavigation.interface.ts
  src/components/ColumnNavigation/index.ts
  src/components/ColumnNavigation/styled-components.ts
Labels: Review Required
