Repository Suada-Learning/suada-components, pull requests merged in 2025-03, with the labels that each got.

#95 feat: add DrawerTips component with styled components and Storybook stories
  src/components/DrawerTips/DrawerTips.stories.tsx
  src/components/DrawerTips/DrawerTips.tsx
  src/components/DrawerTips/drawerTips.interface.ts
  src/components/DrawerTips/index.ts
  src/components/DrawerTips/styled-component.ts
Labels: Review Required

#94 feat: add RadioButton component with styled components and Storybook …
  src/components/RadioButton/RadioButton.stories.tsx
  src/components/RadioButton/RadioButton.tsx
  src/components/RadioButton/index.ts
  src/components/RadioButton/radioButton.interface.ts
Labels: Change(s) requested

#93 feat: add Tabs component with styled components and Storybook stories
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/index.ts
  src/components/Tabs/styled-components.ts
  src/components/Tabs/tabs.interface.ts
Labels: Change(s) requested

#92 feat: add WelcomeUser component with styled components and Storybook stories
  src/components/WelcomeUser/WelcomeUser.stories.tsx
  src/components/WelcomeUser/WelcomeUser.tsx
  src/components/WelcomeUser/index.ts
  src/components/WelcomeUser/styled-components.ts
  src/components/WelcomeUser/welcomeUser.interface.ts
Labels: Change(s) requested

#91 feat: add StatusIndicator component with styled components and Storybook stories
  src/components/StatusIndicator/StatusIndicator.stories.tsx
  src/components/StatusIndicator/StatusIndicator.tsx
  src/components/StatusIndicator/index.ts
  src/components/StatusIndicator/status.interface.ts
  src/components/StatusIndicator/styled-components.ts
Labels: Change(s) requested

#109 feat: update VideoPlayer component and stories with new props and testing libraries
  dist/components/VideoPlayer/Player.js
  dist/components/VideoPlayer/Player.js.map
  dist/components/VideoPlayer/VideoPlayer.stories.d.ts
  dist/components/VideoPlayer/VideoPlayer.stories.js
  dist/components/VideoPlayer/VideoPlayer.stories.js.map
  package.json
  src/components/VideoPlayer/Player.tsx
  src/components/VideoPlayer/VideoPlayer.stories.tsx
  yarn.lock
Labels: Review Required

#126 feat: add suada-admin font in project
  src/App.css
Labels: Ready To Merge

#128 Fix/d.settings icon
  dist/icons/SettingsOutlinedIcon.js
  dist/icons/SettingsOutlinedIcon.js.map
  dist/icons/index.esm.js
  dist/icons/index.esm.js.map
  src/icons/SettingsOutlinedIcon.tsx
Labels: Ready To Merge
